### ISSUE TITLE
Requirements

### ISSUE THREAD

**Issue by viking2009** [u10int/URBAlertView#1]
UIAlertView.m
Line 672:       normalButtonImage = [[self normalButtonImage] resizableImageWithCapInsets:UIEdgeInsetsMake(6.0f, 6.0f, 6.0f, 6.0f) resizingMode:UIImageResizingModeStretch];
        });

resizableImageWithCapInsets:resizingMode: NS_AVAILABLE_IOS(6_0);

so min Deployment Target is 6.0

**Comment by u10int** [comment]
Thanks for pointing that out, @viking2009. I noticed that issue the other day also and just haven't gotten around to updating the code, hopefully today or tomorrow I can.

**Comment by u10int** [comment]
I pushed out an update that fixes this issue so the component will now work on iOS 5.0+.
