### ISSUE TITLE
looks weird sometimes

### ISSUE THREAD

**Issue by MattW86** [u10int/URBAlertView#2]
Hello,

Sometimes alert view looks very weird. I don't know why.  

![ios simulator screen shot 18 07 2013 8 36 05 pm](https://f.cloud.github.com/assets/3792023/818529/462d8d08-ef96-11e2-8780-670a18064f44.png)

**Comment by u10int** [comment]
@MattW86 can you provide the code you're using for instantiating that URBAlertView instance?

**Comment by MattW86** [comment]
```
 Sure.

    NSString *user = [[NSUserDefaults standardUserDefaults] stringForKey:USERNAME];
    NSString *message = [NSString stringWithFormat:@"Hello %@, please enter your password.", user];

    URBAlertView *alertView = [URBAlertView dialogWithTitle:@"Enter Password" message:message];
    [alertView addTextFieldWithPlaceholder:@"password" secure:YES];
    [alertView addButtonWithTitle:@"OK"];
    [alertView showWithAnimation:0];

    __weak ViewController *self_ = self;

    [alertView setHandlerBlock:^(NSInteger buttonIndex, URBAlertView *alertView) {

        for (UITextField *tf in alertView.subviews) {
            [tf resignFirstResponder];
        }

        [alertView hideWithCompletionBlock:^{
            [self_ checkPin:[alertView textForTextFieldAtIndex:0]];
        }];
    }];
```

**Comment by u10int** [comment]
@MattW86 I don't see anything that stands out as weird in the code you posted. Do you happen to have any resizing masks in your views anywhere, or the URBAlertView instance itself? Looks like it's getting resized based on some other metrics somewhere within your app.

**Comment by MattW86** [comment]
I have updated the code and so far I haven't seen that. Maybe previous version had that problem.. I will let you know if it comes back..

Yes.. I am resizing one of the views in my VC. Maybe that is the reason! I will investigate more..

By the way in iOS 5 the following code is not working for some reason..

 for (UITextField *tf in alertView.subviews) {
            [tf resignFirstResponder];
        }

**Comment by u10int** [comment]
Realized I never got back to responding about the issue you commented about regarding resigning the keyboard not working. This should be corrected in my last commit after fixing an issue another user contacted me about. If not, let me know and I'll take a look at it again.
