### ISSUE TITLE
Problem in Retina-4-inch 64Bit iOS7

### ISSUE THREAD

**Issue by balram3429** [u10int/URBAlertView#4]
I am facing a severe issue when using this URBAlertVIew. As instructed, I am using the .h & .m files. The returns warning during building for imcompatible pointer types here

```
- (UIColor *)adjustBrightness:(CGFloat)amount {
float h, s, b, a, w;

if ([self getHue:&h saturation:&s brightness:&b alpha:&a]) {
    b += (amount-1.0);
    b = MAX(MIN(b, 1.0), 0.0);
    return [UIColor colorWithHue:h saturation:s brightness:b alpha:a];
}
else if ([self getWhite:&w alpha:&a]) {
    w += (amount-1.0);
    w = MAX(MIN(w, 1.0), 0.0);
    return [UIColor colorWithWhite:w alpha:a];
}

return nil;
```

}

The problem is : when this is run on iPhone simulator 4 inch its works fine, but when run on 4inch 64bit, the colour fades.
But the Demo App provided with this, works well in all scenarios. Also I do not see any warnings in the above mentioned method in the Demo App.  Here are the attached screens.

![ios simulator screen shot 31-oct-2013 1 49 09 pm](https://f.cloud.github.com/assets/1736969/1444339/490812a2-4205-11e3-83e0-f81e90152253.png)

![ios simulator screen shot 31-oct-2013 1 47 52 pm](https://f.cloud.github.com/assets/1736969/1444338/487b9f3e-4205-11e3-9641-9afda187a28c.png)

**Comment by u10int** [comment]
@balram3429 It sounds like you're only seeing the color fade issue in your custom project? Did you verify you have linked against all of the necessary frameworks? I notice I don't have the required frameworks listed in the installation notes, so will add them here shortly. In addition to the standard Foundation.framework and UIKit.framework, you also need:
- QuartzCore.framework
- Accelerate.framework
- CoreGraphics.framework

Also, can you provide the full warning message Xcode is giving your about incompatible pointer types... something like "Incompatible pointer types sending 'NSString *' to parameter of type 'NSInteger *'".

**Comment by balram3429** [comment]
I have verified all the frameworks in the build settings as well as the framework folder in the demo apps. 
Regarding warnings, it is regarding CGFloat to double conversion in the method I have mentioned. If I change the float to double, the things works well in 4 inch 64but retina but fails on non retina. In non retina it had to be float. 

The warnings are displayed on the
 "&" symbol variables in the mention method.

Hopefully, if you can just create a sample project on Xcode 5 & include the UBRAlertView.h & m files, you can surely see warnings on compiling by choosing different version of simulators.

**Comment by balram3429** [comment]
Here is the full project. Just compile this while selecting 4inch 64bit retina
& 4 inch normal. 
Kindly note this is the project that something I am conceptualizing my idea. 

Sent from my iPhone

Begin forwarded message:

> From: Balram Tiwari tiwari.balram@gmail.com
> Date: October 31, 2013 at 16:35:10 GMT+5:30
> To: Balram Tiwari tiwari.balram@hotmail.com
> Subject: hi
> 
> ## 
> 
> Balram Tiwari

**Comment by u10int** [comment]
I was able to duplicate your issue by creating a new project targeting just iOS 7 and running in 64-bit. It was a simple issue where I was using `float` instead of `CGFloat`, so I updated the repo and it should work fine for you once you update your local copy.
