### ISSUE TITLE
issue on iphone4 - retina 64 Bit  Message is truncated (not visible.)

### ISSUE THREAD

**Issue by balram3429** [u10int/URBAlertView#5]
Hi,
Thank you for the last fix. Now I see another issue with the message. The message displayed is truncated in iPhone-4-retina-64bit but works well in others. 
The issue is::
If I got a two line message, the 2nd line will be truncated, & if I got a 3 line message, the third line will be truncated. 
Here is the screen shots.

![screen shot 2013-11-01 at 9 14 33 am](https://f.cloud.github.com/assets/1736969/1451730/200fcfa4-42a8-11e3-8cb2-a78086b959b4.png)
![screen shot 2013-11-01 at 9 14 45 am](https://f.cloud.github.com/assets/1736969/1451731/2014f7c2-42a8-11e3-8f66-b49adce81e84.png)

**Comment by balram3429** [comment]
Here are the values from file UBRAlertView.m
Method `- (void)layoutComponents`
Line No: 778, 784
The frame values are the same. I think the problem is with Color fading. Also, you can measure the visible difference in the color appearance of the AlertBox message background in both the pictures.

On 4inch-Retina-64Bit

Printing description of self->layout:

```
 (<anonymous struct>) layout = {
  titleRect = origin=(x=21, y=23) size=(width=238, height=21.474)
  messageRect = origin=(x=21, y=52.474) size=(width=238, height=33.404)
  buttonRect = origin=(x=0, y=0) size=(width=0, height=0)
  buttonRegionRect = origin=(x=0, y=0) size=(width=0, height=0)
  textFieldsRect = origin=(x=0, y=0) size=(width=0, height=0)
  }
```

On 4inch-Retina
Printing description of self->layout:

```
(<anonymous struct>) layout = {
  titleRect = origin=(x=21, y=23) size=(width=238, height=21.473999)
  messageRect = origin=(x=21, y=52.473999) size=(width=238, height=33.403999)
  buttonRect = origin=(x=0, y=0) size=(width=0, height=0)
  buttonRegionRect = origin=(x=0, y=0) size=(width=0, height=0)
  textFieldsRect = origin=(x=0, y=0) size=(width=0, height=0)
}
```

**Comment by u10int** [comment]
I found the issue with the last line of text being cut off, which was due to the title and message frame heights not being rounded up to the nearest integer. Text is rendered slightly differently in iOS 7, which is likely the reason the issue only appeared now. I have corrected the issue and pushed the changes to the repo which should fix this issue for your.
