### ISSUE TITLE
Keyboard not resigning in iOS5 - 3.5 Inch Retina

### ISSUE THREAD

**Issue by balram3429** [u10int/URBAlertView#6]
Just noticed another issue. When the alert view is having a textField then, the KeyBoard do not resign on pressing either of the buttons in alertView (like ok or cancel), but does resign when keybaord's "Done" button is pressed. 
This is happening in iOS5 retina 3.5 inch. Here is the simple piece of code.

```
self.alertView = nil;
self.alertView = [URBAlertView dialogWithTitle:@"Add Stuff" message:@"Provide some stuff."];
[self.alertView addButtonWithTitle:@"Cancel"];
[self.alertView addButtonWithTitle:@"Save"];
[self.alertView addTextFieldWithPlaceholder:@"Add a Stuff." secure:NO];
[self.alertView setHandlerBlock:^(NSInteger buttonIndex, URBAlertView *alertView) {
    if(buttonIndex == 1) {
        if([[[alertView textForTextFieldAtIndex:0] stringByTrimmingCharactersInSet:[NSCharacterSet whitespaceAndNewlineCharacterSet]] length]) {
            [btDBOperation addStuff:[[[alertView textForTextFieldAtIndex:0] stringByTrimmingCharactersInSet:[NSCharacterSet whitespaceCharacterSet]] uppercaseString]];
        }
    }
    [alertView hideWithCompletionBlock:^{
        [_self resignFirstResponder];
        [_self refreshDashBoardData];
        [_self actionBtn:nil];
    }];
}];
[self.alertView showWithAnimation:URBAlertAnimationFlipVertical];
```

Attached screens

![ios simulator screen shot 06-nov-2013 11 03 16 am](https://f.cloud.github.com/assets/1736969/1480285/8d45d662-46a5-11e3-8b00-bbf8279634d1.png)
![ios simulator screen shot 06-nov-2013 11 05 28 am](https://f.cloud.github.com/assets/1736969/1480286/8dc46d7e-46a5-11e3-896d-4f747685ac79.png)

**Comment by u10int** [comment]
I have implemented a fix for the keyboard not resigning when closing the alert view via the buttons. I also added support for some iOS7-specific methods for sizing text since the previous ones are deprecated as of iOS 7. So you will want to make sure you are compiling in Xcode 5 that has the iOS 7 SDK available to prevent compiler warnings about these methods not being declared.
